### ISSUE TITLE
not showing in sources

### ISSUE THREAD

**Issue by madmaxgrey** [scaledteam/obs-image-reaction#6]
i added all the files in the correct locations and when i boot up obs it isn't avaliable in sources

**Comment by csBlackWolf** [comment]
It is working fine for me, on windows 10 with OBS 28.0.1.

![grafik](https://user-images.githubusercontent.com/30509936/191755797-01b282fb-6fb1-493c-b11d-43d7c95133ec.png)

It could be helpful if you can add some more information.

What is you OBS Version and OS?
Can you attach your OBS Log?

**Comment by ashmanix** [comment]
I had the same issue with OSB v28 using Windows 10 on an older PC and on a Mac where I had compiled the code myself for an Arm 1 mac. I ended up forking this repo and updating it to the new OBS plugin template and recompiling (for all OS's) and it worked again.

You can have a look at the pull request I've made [here](https://github.com/scaledteam/obs-image-reaction/pull/7) for this repo and try one of the downloads to see if that fixes the issue.

**Comment by burner-208** [comment]
> I had the same issue with OSB v28 using Windows 10 on an older PC and on a Mac where I had compiled the code myself for an Arm 1 mac. I ended up forking this repo and updating it to the new OBS plugin template and recompiling (for all OS's) and it worked again.
> 
> You can have a look at the pull request I've made [here](https://github.com/scaledteam/obs-image-reaction/pull/7) for this repo and try one of the downloads to see if that fixes the issue.

hey man, i downloaded your version (mac os 10.15 on obs version 28) and installed it, but its not showing in sources. anything i need to do other than click install? thanks !
